// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"database/sql"
)

type List struct {
	ID     int32  `json:"id"`
	Author int32  `json:"author"`
	Header string `json:"header"`
}

type Task struct {
	ID         int32         `json:"id"`
	ListID     int32         `json:"list_id"`
	ParentTask sql.NullInt32 `json:"parent_task"`
	Task       string        `json:"task"`
	Complete   bool          `json:"complete"`
}

type User struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Hash     []byte `json:"hash"`
}
